services:
  - type: web
    name: shiningblogs-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    headers:
      - source: "/*"
        headers:
          - key: "X-Frame-Options"
            value: "DENY"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"